# Generated by Django 4.0.4 on 2022-06-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='obs',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
